import React, { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { 
  ArrowUpRight, 
  ArrowDownRight, 
  DollarSign, 
  Activity, 
  TrendingUp, 
  Clock,
  CheckCircle2,
  AlertCircle
} from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';

export default function Home() {
  const { data: signals } = useQuery({
    queryKey: ['signals'],
    queryFn: () => base44.entities.Signal.list({ sort: { created_date: -1 }, limit: 5 }),
    initialData: []
  });

  const { data: trades } = useQuery({
    queryKey: ['trades'],
    queryFn: () => base44.entities.Trade.list({ sort: { created_date: -1 }, limit: 5 }),
    initialData: []
  });

  const { data: pairs } = useQuery({
    queryKey: ['pairs'],
    queryFn: () => base44.entities.CurrencyPair.list({ limit: 4 }),
    initialData: []
  });

  return (
    <div className="space-y-8 max-w-7xl mx-auto">
      {/* Welcome Section */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold text-white tracking-tight">Market Overview</h1>
          <p className="text-slate-400 mt-1">AI Trading Analysis & Portfolio Performance</p>
        </div>
        <div className="flex gap-3">
          <Button variant="outline" className="border-slate-700 text-slate-300 hover:bg-slate-800 hover:text-white">
            <Clock className="w-4 h-4 mr-2" /> History
          </Button>
          <Button className="bg-emerald-600 hover:bg-emerald-700 text-white shadow-lg shadow-emerald-900/20">
            <TrendingUp className="w-4 h-4 mr-2" /> New Analysis
          </Button>
        </div>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {[
          { label: "Total Balance", value: "$24,560.00", sub: "+$1,240 (5.4%)", icon: DollarSign, color: "text-emerald-400" },
          { label: "Active Trades", value: "8", sub: "3 Pending Orders", icon: Activity, color: "text-blue-400" },
          { label: "Win Rate (AI)", value: "78.4%", sub: "Last 30 Days", icon: CheckCircle2, color: "text-purple-400" },
          { label: "Risk Exposure", value: "Low", sub: "1.2% of Equity", icon: AlertCircle, color: "text-orange-400" }
        ].map((stat, i) => (
          <Card key={i} className="bg-slate-900/50 border-slate-800 backdrop-blur-sm">
            <CardContent className="p-6">
              <div className="flex justify-between items-start">
                <div>
                  <p className="text-sm font-medium text-slate-400">{stat.label}</p>
                  <h3 className="text-2xl font-bold text-white mt-2">{stat.value}</h3>
                  <p className="text-xs text-slate-500 mt-1">{stat.sub}</p>
                </div>
                <div className={`p-3 rounded-xl bg-slate-800/50 ${stat.color}`}>
                  <stat.icon className="w-5 h-5" />
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Active Signals */}
        <Card className="lg:col-span-2 bg-slate-900/50 border-slate-800 backdrop-blur-sm">
          <CardHeader>
            <CardTitle className="text-white flex items-center justify-between">
              <span>Live AI Signals</span>
              <Badge variant="outline" className="border-emerald-500/30 text-emerald-400 bg-emerald-500/10 animate-pulse">
                Live Feed
              </Badge>
            </CardTitle>
            <CardDescription className="text-slate-400">
              Latest trading opportunities generated by the AI engine.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {signals.map((signal) => (
                <div key={signal.id} className="group flex items-center justify-between p-4 rounded-xl bg-slate-800/30 border border-slate-800 hover:border-slate-700 transition-all hover:bg-slate-800/50">
                  <div className="flex items-center gap-4">
                    <div className={`p-2.5 rounded-lg ${signal.type === 'BUY' ? 'bg-emerald-500/10 text-emerald-400' : 'bg-rose-500/10 text-rose-400'}`}>
                      {signal.type === 'BUY' ? <ArrowUpRight className="w-5 h-5" /> : <ArrowDownRight className="w-5 h-5" />}
                    </div>
                    <div>
                      <h4 className="font-bold text-slate-200">{signal.pair}</h4>
                      <div className="flex items-center gap-2 mt-1">
                        <Badge variant="secondary" className="bg-slate-800 text-slate-400 text-[10px] h-5">
                          {signal.strategy}
                        </Badge>
                        <span className="text-xs text-slate-500">
                           Entry: <span className="text-slate-300">{signal.entry_price}</span>
                        </span>
                      </div>
                    </div>
                  </div>
                  
                  <div className="flex items-center gap-6">
                    <div className="hidden sm:block text-right">
                      <div className="flex items-center gap-1 justify-end mb-1">
                        <span className="text-xs text-slate-400">Confidence</span>
                        <span className="text-xs font-bold text-emerald-400">{signal.confidence}%</span>
                      </div>
                      <Progress value={signal.confidence} className="w-24 h-1.5 bg-slate-700" indicatorClassName="bg-emerald-500" />
                    </div>
                    <Button size="sm" variant="outline" className="border-slate-700 hover:bg-slate-700 text-slate-300">
                      Execute
                    </Button>
                  </div>
                </div>
              ))}
              {signals.length === 0 && (
                <div className="text-center py-10 text-slate-500">Waiting for signals...</div>
              )}
            </div>
          </CardContent>
        </Card>

        {/* Market Watch */}
        <Card className="bg-slate-900/50 border-slate-800 backdrop-blur-sm">
          <CardHeader>
            <CardTitle className="text-white">Market Watch</CardTitle>
            <CardDescription className="text-slate-400">
              Real-time pricing for major pairs.
            </CardDescription>
          </CardHeader>
          <CardContent className="p-0">
            <div className="divide-y divide-slate-800">
              {pairs.map((pair) => (
                <div key={pair.id} className="flex items-center justify-between p-4 hover:bg-slate-800/30 transition-colors">
                  <div className="flex items-center gap-3">
                    <div className="w-8 h-8 rounded-full bg-slate-800 flex items-center justify-center text-xs font-bold text-slate-300 border border-slate-700">
                      {pair.symbol.substring(0,1)}
                    </div>
                    <div>
                      <p className="font-medium text-slate-200">{pair.symbol}</p>
                      <p className="text-xs text-slate-500">Vol: {pair.volatility}</p>
                    </div>
                  </div>
                  <div className="text-right">
                    <p className="font-medium text-slate-200">{pair.current_price}</p>
                    <p className={`text-xs flex items-center justify-end ${pair.change_24h >= 0 ? 'text-emerald-400' : 'text-rose-400'}`}>
                      {pair.change_24h >= 0 ? '+' : ''}{pair.change_24h}%
                    </p>
                  </div>
                </div>
              ))}
            </div>
            <div className="p-4">
              <Button className="w-full bg-slate-800 hover:bg-slate-700 text-slate-300">View All Pairs</Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}