import React, { useState, useEffect } from 'react';
import { useQuery } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Input } from '@/components/ui/input';
import { Progress } from '@/components/ui/progress';
import { Badge } from '@/components/ui/badge';
import { Play, RotateCcw, BarChart, FileText, ChevronRight, TrendingUp, TrendingDown, Clock, Activity, Calendar, DollarSign, Zap, Target } from 'lucide-react';
import { toast } from 'sonner';

export default function BacktestPanel({ preselectedBot }) {
  const [isRunning, setIsRunning] = useState(false);
  const [progress, setProgress] = useState(0);
  const [results, setResults] = useState(null);
  const [selectedBotId, setSelectedBotId] = useState(preselectedBot?.id || '');
  const [selectedSymbol, setSelectedSymbol] = useState('EURUSD');
  const [selectedTimeframe, setSelectedTimeframe] = useState('H1');
  const [initialBalance, setInitialBalance] = useState(10000);

  const { data: bots } = useQuery({
    queryKey: ['bots-list'],
    queryFn: () => base44.entities.BotConfig.list(),
    initialData: []
  });

  useEffect(() => {
    if (preselectedBot) {
        setSelectedBotId(preselectedBot.id);
    }
  }, [preselectedBot]);

  const selectedBotConfig = bots.find(b => b.id === selectedBotId);

  const runBacktest = async () => {
    if (!selectedBotConfig) {
      toast.error('Please select a bot to backtest');
      return;
    }

    setIsRunning(true);
    setProgress(0);
    setResults(null);
    
    try {
      // Simulate progress while running actual backtest
      const progressInterval = setInterval(() => {
        setProgress(prev => Math.min(prev + 8, 95));
      }, 200);

      const response = await base44.functions.invoke('runBacktest', {
        botId: selectedBotConfig.id,
        symbol: selectedSymbol,
        timeframe: selectedTimeframe,
        initialBalance: initialBalance,
        startDate: null,
        endDate: null
      });

      clearInterval(progressInterval);
      setProgress(100);

      if (response.data.success) {
        setResults(response.data.results);
        toast.success('Backtest completed successfully');
      } else {
        throw new Error(response.data.error || 'Backtest failed');
      }
    } catch (error) {
      console.error('Backtest error:', error);
      toast.error('Backtest failed: ' + (error.response?.data?.error || error.message));
      setResults(null);
    } finally {
      setIsRunning(false);
    }
  };

  const exportReport = () => {
    if (!results || !selectedBotConfig) return;
    
    try {
      const reportData = {
        botName: selectedBotConfig.name,
        strategy: selectedBotConfig.strategy_type,
        riskLevel: selectedBotConfig.risk_level,
        testDate: new Date().toLocaleDateString(),
        results: {
          totalTrades: results.totalTrades,
          winRate: results.winRate,
          totalPnl: results.totalPnl,
          profitFactor: results.profitFactor,
          maxDrawdown: results.maxDrawdown,
          sharpeRatio: results.sharpeRatio
        }
      };
      
      const reportText = `
ForexTouchAI - Backtest Report
================================

Bot: ${reportData.botName}
Strategy: ${reportData.strategy}
Risk Level: ${reportData.riskLevel}
Test Date: ${reportData.testDate}

PERFORMANCE METRICS
-------------------
Total Trades: ${reportData.results.totalTrades}
Win Rate: ${reportData.results.winRate}%
Total Net Profit: $${reportData.results.totalPnl.toLocaleString()}
Profit Factor: ${reportData.results.profitFactor}
Max Drawdown: ${reportData.results.maxDrawdown}%
Sharpe Ratio: ${reportData.results.sharpeRatio}

Report generated by ForexTouchAI
      `.trim();
      
      const blob = new Blob([reportText], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `backtest-${selectedBotConfig.name}-${Date.now()}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      toast.success('Report exported successfully');
    } catch (error) {
      toast.error('Failed to export report');
      console.error('Export error:', error);
    }
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
      <div className="lg:col-span-1 space-y-6">
        <Card className="bg-slate-900/50 border-slate-800 backdrop-blur-sm">
          <CardHeader>
            <CardTitle className="text-white text-lg flex items-center gap-2">
              <Clock className="w-5 h-5 text-emerald-400" /> Configuration
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-5">
            <div className="space-y-2">
              <Label className="text-slate-200">Select Bot to Backtest</Label>
              <Select value={selectedBotId} onValueChange={setSelectedBotId}>
                <SelectTrigger className="bg-slate-950 border-slate-800 text-white">
                  <SelectValue placeholder="Select a bot..." />
                </SelectTrigger>
                <SelectContent>
                  {bots.map(bot => (
                      <SelectItem key={bot.id} value={bot.id}>{bot.name}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
              {selectedBotConfig && (
                  <div className="flex flex-wrap gap-2 mt-2">
                      <Badge variant="outline" className={`
                          ${selectedBotConfig.risk_level === 'HIGH' ? 'bg-rose-500/10 text-rose-400 border-rose-500/20' : 
                            selectedBotConfig.risk_level === 'MEDIUM' ? 'bg-amber-500/10 text-amber-400 border-amber-500/20' : 
                            'bg-emerald-500/10 text-emerald-400 border-emerald-500/20'}
                      `}>
                          Risk: {selectedBotConfig.risk_level}
                      </Badge>
                      <Badge variant="outline" className="bg-blue-500/10 text-blue-400 border-blue-500/20">
                          {selectedBotConfig.strategy_type.replace('_', ' ')}
                      </Badge>
                  </div>
              )}
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                  <Label className="flex items-center gap-2 text-slate-300">
                      <Activity className="w-3.5 h-3.5 text-blue-400" /> Symbol
                  </Label>
                  <Select value={selectedSymbol} onValueChange={setSelectedSymbol}>
                  <SelectTrigger className="bg-slate-950 border-slate-800 text-slate-200">
                      <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                      {selectedBotConfig?.pairs?.length > 0 ? (
                          selectedBotConfig.pairs.map(pair => (
                              <SelectItem key={pair} value={pair.replace('/', '')}>{pair}</SelectItem>
                          ))
                      ) : (
                          <>
                          <SelectItem value="EURUSD">EUR/USD</SelectItem>
                          <SelectItem value="GBPUSD">GBP/USD</SelectItem>
                          <SelectItem value="USDJPY">USD/JPY</SelectItem>
                          <SelectItem value="XAUUSD">XAU/USD (Gold)</SelectItem>
                          </>
                      )}
                  </SelectContent>
                  </Select>
              </div>

              <div className="space-y-2">
                  <Label className="flex items-center gap-2 text-slate-300">
                      <Zap className="w-3.5 h-3.5 text-purple-400" /> Timeframe
                  </Label>
                  <Select value={selectedTimeframe} onValueChange={setSelectedTimeframe}>
                  <SelectTrigger className="bg-slate-950 border-slate-800 text-slate-200">
                      <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                      <SelectItem value="M15">M15 (15 Minutes)</SelectItem>
                      <SelectItem value="H1">H1 (1 Hour)</SelectItem>
                      <SelectItem value="H4">H4 (4 Hours)</SelectItem>
                      <SelectItem value="D1">D1 (Daily)</SelectItem>
                  </SelectContent>
                  </Select>
              </div>
            </div>

            <div className="space-y-2">
              <Label className="flex items-center gap-2 text-slate-300">
                  <Calendar className="w-3.5 h-3.5 text-amber-400" /> Period
              </Label>
              <div className="grid grid-cols-2 gap-2">
                <Input type="date" className="bg-slate-950 border-slate-800 text-xs text-slate-300" />
                <Input type="date" className="bg-slate-950 border-slate-800 text-xs text-slate-300" />
              </div>
            </div>

            <div className="space-y-2">
              <Label className="flex items-center gap-2 text-slate-300">
                  <DollarSign className="w-3.5 h-3.5 text-emerald-400" /> Initial Balance
              </Label>
              <Input type="number" defaultValue="10000" className="bg-slate-950 border-slate-800 text-slate-200" />
            </div>

            <Button 
              className="w-full bg-emerald-600 hover:bg-emerald-700 mt-4" 
              onClick={runBacktest}
              disabled={isRunning}
            >
              {isRunning ? 'Running Simulation...' : <><Play className="w-4 h-4 mr-2" /> Start Backtest</>}
            </Button>
          </CardContent>
        </Card>
      </div>

      <div className="lg:col-span-3 space-y-6">
        {/* Results Area */}
        <Card className="bg-slate-900/50 border-slate-800 backdrop-blur-sm min-h-[400px] flex flex-col">
          <CardHeader className="flex flex-row items-center justify-between">
            <CardTitle className="text-white text-lg flex items-center gap-2">
              <BarChart className="w-5 h-5 text-blue-400" /> Simulation Results
            </CardTitle>
            {results && (
              <Button 
                variant="outline" 
                size="sm" 
                className="bg-emerald-500/10 border-emerald-500/30 text-emerald-400 hover:bg-emerald-500/20"
                onClick={exportReport}
              >
                <FileText className="w-4 h-4 mr-2" /> Export Report
              </Button>
            )}
          </CardHeader>
          <CardContent className="flex-1">
            {isRunning ? (
              <div className="flex flex-col items-center justify-center h-full py-20">
                <div className="w-full max-w-md space-y-4">
                  <div className="flex justify-between text-sm text-slate-400">
                    <span>Processing tick data...</span>
                    <span>{progress}%</span>
                  </div>
                  <Progress value={progress} className="h-2 bg-slate-800" indicatorClassName="bg-emerald-500" />
                  <p className="text-xs text-center text-slate-500 animate-pulse">Calculating indicators and trade logic on 12 months of historical data</p>
                </div>
              </div>
            ) : results ? (
              <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
                {/* Key Metrics */}
                <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4">
                  <div className="bg-slate-950/50 p-4 rounded-lg border border-slate-800">
                    <div className="text-slate-500 text-xs mb-1">Total Net Profit</div>
                    <div className="text-emerald-400 font-bold text-lg">+${results.totalPnl.toLocaleString()}</div>
                  </div>
                  <div className="bg-slate-950/50 p-4 rounded-lg border border-slate-800">
                    <div className="text-slate-500 text-xs mb-1">Win Rate</div>
                    <div className="text-blue-400 font-bold text-lg">{results.winRate}%</div>
                  </div>
                  <div className="bg-slate-950/50 p-4 rounded-lg border border-slate-800">
                    <div className="text-slate-500 text-xs mb-1">Profit Factor</div>
                    <div className="text-slate-200 font-bold text-lg">{results.profitFactor}</div>
                  </div>
                  <div className="bg-slate-950/50 p-4 rounded-lg border border-slate-800">
                    <div className="text-slate-500 text-xs mb-1">Max Drawdown</div>
                    <div className="text-rose-400 font-bold text-lg">{results.maxDrawdown}%</div>
                  </div>
                  <div className="bg-slate-950/50 p-4 rounded-lg border border-slate-800">
                    <div className="text-slate-500 text-xs mb-1">Total Trades</div>
                    <div className="text-slate-200 font-bold text-lg">{results.totalTrades}</div>
                  </div>
                  <div className="bg-slate-950/50 p-4 rounded-lg border border-slate-800">
                    <div className="text-slate-500 text-xs mb-1">Sharpe Ratio</div>
                    <div className="text-amber-400 font-bold text-lg">{results.sharpeRatio}</div>
                  </div>
                </div>

                {/* Equity Chart Placeholder */}
                <div className="bg-slate-950/30 border border-slate-800 rounded-lg p-6 h-64 relative">
                  <div className="absolute inset-0 flex items-center justify-center opacity-30">
                    <TrendingUp className="w-24 h-24 text-emerald-500" />
                  </div>
                  <div className="flex items-end justify-between h-full w-full gap-1 pt-8 px-4">
                    {[30, 35, 32, 40, 45, 42, 48, 55, 52, 58, 65, 62, 70, 75, 72, 80, 85, 82, 90, 95].map((h, i) => (
                      <div key={i} className="w-full bg-emerald-500/20 hover:bg-emerald-500/40 transition-colors rounded-t" style={{height: `${h}%`}}></div>
                    ))}
                  </div>
                </div>
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center h-full text-slate-500 py-20">
                <Play className="w-12 h-12 mb-4 opacity-20" />
                <p>Select parameters and start backtest to see results</p>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}